name: Delete Environment

on:
  delete:
  pull_request:
    types: [closed]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  delete:
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    name: Delete Environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure CLI login
        run: az login --service-principal --tenant ${{ vars.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: ADE Delete
        uses: colbylwilliams/deployment-environments@v1
        with:
          action: delete
