name: Create Environment

on:
  create:
  pull_request:
    types: [opened, reopened]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  create:
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    name: Create Environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure CLI login
        run: az login --service-principal --tenant ${{ vars.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: ADE Create
        uses: colbylwilliams/deployment-environments@v1
        with:
          action: create

      - name: AZD Install
        run: curl -fsSL https://aka.ms/install-azd.sh | bash

      - name: AZD Login
        run: azd auth login --tenant-id ${{ vars.AZURE_TENANT_ID }} --client-id ${{ secrets.AZURE_CLIENT_ID }} --client-secret ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: AZD Init
        run: |
          azd config set alpha.resourceGroupDeployments on
          azd init --location eastus2 --subscription $ADE_SUBSCRIPTION --environment $ADE_NAME
          azd env set AZURE_RESOURCE_GROUP $ADE_RESOURCE_GROUP

      - name: AZD Provision
        run: |
          azd provision
          azd env get-values

      - name: AZD Deploy
        run: azd deploy --all
